language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  #allow_failures:
    #- php: 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer global require fxp/composer-asset-plugin:~1.1.3
